version: '3.1'
services:
  db:
    image: mariadb:10.7
    volumes:
      - database:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - ./ownrecipes-api/.env
      - ./ownrecipes-api/.env.development
  api:
    build: ./ownrecipes-api/
    command: python manage.py runserver 0.0.0.0:5210
    volumes:
      - ./ownrecipes-api/v1:/code/v1
      - static-files:/code/static-files
      - site-media:/code/site-media
    depends_on:
      - db
    ports:
      - "5210:5210"
    env_file:
      - ./ownrecipes-api/.env
      - ./ownrecipes-api/.env.development
  web:
    build: ./ownrecipes-web/
    volumes:
      - ./ownrecipes-web/src:/code/src
      - '/code/node_modules'
    profiles: ["all"]
    ports:
      - "8080:8080"
    env_file:
      - ./ownrecipes-web/.env
      - ./ownrecipes-web/.env.development
volumes:
  database:
  static-files:
  site-media:
