version: '3.1'
services:
  api:
    image: ownrecipes/ownrecipes-api
    command: /startup/prod-entrypoint.sh
    restart: on-failure
    volumes:
      - static-files:/code/static-files
      - site-media:/code/site-media
    env_file:
      - .env.docker.production.api
  web:
    image: ownrecipes/ownrecipes-web
    volumes:
      - public-ui:/code/public
    env_file:
      - .env.docker.production.web
  nginx:
    image: ownrecipes/ownrecipes-nginx
    command: ./start.sh
    volumes:
      - static-files:/var/www/html/ownrecipes-static/static-files
      - site-media:/var/www/html/ownrecipes-static/site-media
      - public-ui:/var/www/html/ownrecipes-static/public-ui
    depends_on:
      - api
      - web
    env_file:
      - .env.docker.production.api
volumes:
  public-ui:
  static-files:
  site-media:
